version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: "./wait-for-it.sh db:3306 --strict --timeout=300 -- npm start"
    env_file: .env
    environment:
      DATABASE_HOST: "db"
      DATABASE_USER: ${DB_USER}
      DATABASE_NAME: ${DB_DATABASE}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      MYSQL_HOST: "db"
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3307:3306"
